### ISSUE TITLE
reversed search not symmetric

### ISSUE THREAD

**Issue by abyrd** [bliksemlabs/rrrr#20] opened 2013-07-22 17:09 UTC
There is something asymmetric about forward/backward searches. The request reversal seems ok (note that the router is ignoring the transfer and time bounds for now) but the forward search gives a later arrival time than the one specified in the original arriveby search.

```
Searching with request: 
-- Router Request --
from:  Katwijk a/d Rijn, Callaoweg [6183]
to:    Zoetermeer, Pruimengaarde [5795]
time:  12:32:12 [45132]
speed: 1.500000 m/sec
arrive-by: true
max xfers: 4
max time:     --   
midnight: 00:00:00 -1D 
day mask: 00000000000000000000000010000000
includes: 7 
midnight: 00:00:00 
day mask: 00000000000000000000000100000000
includes: 8 
midnight: 00:00:00 +1D 
day mask: 00000000000000000000001000000000
includes: 9 
day mask: 00000000000000000000001110000000
includes: 7 8 9 

A 3 VEHICLES 
walk;walk;Katwijk a/d Rijn, Zanderijpad;11:16:00;Katwijk a/d Rijn, Callaoweg;11:12:52
bus 31 (Leiden - Katwijk via Noordboulevard);Leiden CS via Tramstraat;Leiden, Centraal Station;11:31:00;Katwijk a/d Rijn, Zanderijpad;11:16:00
walk;walk;Leiden, Centraal Station;11:33:00;Leiden, Centraal Station;11:31:28
bus 365 (Schiphol - Zoetermeer via Leiden);Zoetermeer via Leiden CS;Zoetermeer, Centrum West;11:59:00;Leiden, Centraal Station;11:33:00
walk;walk;Zoetermeer, Centrum West;12:02:00;Zoetermeer, Centrum West;12:01:56
bus 165 (Alphen a/d Rijn - Zoetermeer CW);Alphen a/d Rijn;Zoetermeer, Pruimengaarde;12:07:00;Zoetermeer, Centrum West;12:02:00

Repeating search with reversed request: 
-- Router Request --
from:  Katwijk a/d Rijn, Callaoweg [6183]
to:    Zoetermeer, Pruimengaarde [5795]
time:  11:12:48 [40368]
speed: 1.500000 m/sec
arrive-by: false
max xfers: 2
max time:  12:32:12 -1D
midnight: 00:00:00 -1D 
day mask: 00000000000000000000000010000000
includes: 7 
midnight: 00:00:00 
day mask: 00000000000000000000000100000000
includes: 8 
midnight: 00:00:00 +1D 
day mask: 00000000000000000000001000000000
includes: 9 
day mask: 00000000000000000000001110000000
includes: 7 8 9 

A 3 VEHICLES 
bus 165 (Alphen a/d Rijn - Zoetermeer CW);Alphen a/d Rijn;Zoetermeer, Centrum West;13:02:00;Zoetermeer, Pruimengaarde;13:07:00
walk;walk;Zoetermeer, Centrum West;12:29:00;Zoetermeer, Centrum West;12:29:04
bus 365 (Schiphol - Zoetermeer via Leiden);Zoetermeer via Leiden CS;Leiden, Centraal Station;12:03:00;Zoetermeer, Centrum West;12:29:00
walk;walk;Leiden, Centraal Station;12:01:00;Leiden, Centraal Station;12:02:32
bus 31 (Leiden - Katwijk via Noordboulevard);Leiden CS via Tramstraat;Katwijk, Poolster;11:38:00;Leiden, Centraal Station;12:01:00
walk;walk;Noordwijk, Space Expo;11:31:00;Katwijk, Poolster;11:35:52
bus 30 (Leiden - Katwijk via Biltlaan);Katwijk via Biltlaan;Katwijk a/d Rijn, Molentuinweg;11:24:00;Noordwijk, Space Expo;11:31:00
walk;walk;Katwijk a/d Rijn, Callaoweg;11:12:48;Katwijk a/d Rijn, Molentuinweg;11:22:56
```

**Comment by abyrd** [comment] 2013-07-22 18:28
Rebuilt timetable from new data etc. but still a bit off. Here's a particularly strange case where the forward search uses the same line but does not board the proper trip:

```
-- Router Request --
from:  Voorst-Empe, Voorst-Empe [2578]
to:    Engwierum, Statendijk [1219]
time:  13:58:12 [50293]
speed: 1.500000 m/sec
arrive-by: true

A 5 VEHICLES 
walk;walk;Voorst-Empe spoor 1;10:19:00;Voorst-Empe, Voorst-Empe;10:18:52
stoptrein;Zutphen;Zutphen spoor 2a;10:24:00;Voorst-Empe spoor 1;10:19:00
walk;walk;Zutphen spoor 3;10:33:00;Zutphen spoor 2a;10:31:44
Intercity;Zwolle;Zwolle spoor 5b;11:11:00;Zutphen spoor 3;10:33:00
walk;walk;Zwolle spoor 6;11:23:00;Zwolle spoor 5b;11:21:40
Intercity;Leeuwarden;Leeuwarden spoor 4;12:17:00;Zwolle spoor 6;11:23:00
walk;walk;Leeuwarden spoor 8;12:21:00;Leeuwarden spoor 4;12:20:16
stoptrein;Groningen;Buitenpost spoor 1;12:45:00;Leeuwarden spoor 8;12:21:00
walk;walk;Buitenpost, Station;12:48:00;Buitenpost spoor 1;12:47:28
bus 63 (Dokkum - Buitenpost);Dokkum Busstation;Engwierum, Statendijk;13:09:00;Buitenpost, Station;12:48:00

Repeating search with reversed request: 
-- Router Request --
from:  Voorst-Empe, Voorst-Empe [2578]
to:    Engwierum, Statendijk [1219]
time:  10:18:48 [37128]
speed: 1.500000 m/sec
arrive-by: false

A 5 VEHICLES 
bus 63 (Dokkum - Buitenpost);Dokkum Busstation;Buitenpost, Station;13:48:00;Engwierum, Statendijk;14:09:00
walk;walk;Buitenpost spoor 2;12:58:00;Buitenpost, Station;12:58:04
Sneltrein;Leeuwarden;Groningen spoor 6a;12:40:00;Buitenpost spoor 2;12:58:00
walk;walk;Groningen spoor 6b;12:34:00;Groningen spoor 6a;12:36:12
Sprinter;Groningen;Zwolle spoor 14;11:26:00;Groningen spoor 6b;12:34:00
walk;walk;Zwolle spoor 5b;11:11:00;Zwolle spoor 14;11:12:00
Intercity;Zwolle;Zutphen spoor 3;10:33:00;Zwolle spoor 5b;11:11:00
walk;walk;Zutphen spoor 2a;10:24:00;Zutphen spoor 3;10:25:16
stoptrein;Zutphen;Voorst-Empe spoor 1;10:19:00;Zutphen spoor 2a;10:24:00
walk;walk;Voorst-Empe, Voorst-Empe;10:18:48;Voorst-Empe spoor 1;10:18:56
```

**Comment by koch-t** [comment] 2013-07-23 16:40
Andrew did you notice that there is a teleport in that advice?

boarding at 10:24 and alighting at 10:19??
stoptrein;Zutphen;Zutphen spoor 2a;10:24:00;Voorst-Empe spoor 1;10:19:00
Plus it's a train towards Zutphen but you board it at Zutphen to go to Voorst-Empe?

//edit
Oh never mind, in the forward search origin and destion are reversed?

**Comment by koch-t** [comment] 2013-07-23 16:51
In the Voorste-Emple -> Engwierium trip it starts going wrong at Zwolle, could you check some things for me in the gtfsdb?

Whether there is a transfer from platfrom 14 to 5. 
Whether there is a transfer from platfrom 5 to 14.

**Comment by abyrd** [comment] 2013-07-23 17:04
On 07/23/2013 06:40 PM, skywave wrote:

> Andrew did you notice that there is a teleport in that advice?
> 
> boarding at 10:24 and alighting at 10:19??
> stoptrein;Zutphen;Zutphen spoor 2a;10:24:00;Voorst-Empe spoor 1;10:19:00
> Plus it's a train towards Zutphen but you board it at Zutphen to go to
> Voorst-Empe?

Right, it's an arrive-by request so everything is backward. I should
really write a result dump function that accounts for that. It would
make debugging so much less painful.

-A

**Comment by abyrd** [comment] 2013-07-23 18:00
zl|14 zl|5b 9 92.1475570308113
zl|5b zl|14 9 92.1479370297562

Both transfers are present.

**Comment by koch-t** [comment] 2013-07-23 18:35
You have a idea where this problem is? Was it present before the overnight patches? Maybe add trip_id's back again so i can check in the data.

**Comment by koch-t** [comment] 2013-10-04 18:56
Problem seems to be back?

```
-- Router Request --
from:  Den Haag, Van Speijkstraat [9702]
to:    Den Haag HS|4 [38996]
time:  00:41:00 [22215]
speed: 1.500000 m/sec
arrive-by: false
max xfers: 5
max time:     --   
mode: transit

ITIN 1 rides 
WALK    -2  -2  9702 10120 00:41:00 00:53:56 +0.0 ;walk;walk;Den Haag, Van Speijkstraat;Den Haag, Alexanderplein;
BUS  2420   3 10120 10248 01:37:00 01:44:00 +0.0 ;N1;N1 Station HS/Centrum;;Den Haag, Alexanderplein;Den Haag, Station Hollands Spoor|H;
WALK    -2  -2 10248 38996 01:44:00 01:45:24 +0.0 ;walk;walk;Den Haag, Station Hollands Spoor|H;Den Haag HS|4;

ITIN 2 rides 
WALK    -2  -2  9702 10323 00:41:00 00:59:08 +0.0 ;walk;walk;Den Haag, Van Speijkstraat;Den Haag, Brouwersgracht;
BUS  3661   1 10323 10452 01:04:00 01:08:00 +0.0 ;N4;N4 Wateringen/Rijswijk;;Den Haag, Brouwersgracht;Den Haag, De la Reyweg;
WALK    -2  -2 10452 10221 01:08:00 01:28:48 +0.0 ;walk;walk;Den Haag, De la Reyweg;Den Haag, Station Moerwijk;
BUS  4059   3 10221 10249 01:37:00 01:43:00 +0.0 ;N4;N4 Centrum/Buitenhof;;Den Haag, Station Moerwijk;Den Haag, Station Hollands Spoor|I;
WALK    -2  -2 10249 38996 01:43:00 01:44:36 +0.0 ;walk;walk;Den Haag, Station Hollands Spoor|I;Den Haag HS|4;
Repeated search with reversed request: 
-- Router Request --
from:  Den Haag, Van Speijkstraat [9702]
to:    Den Haag HS|4 [38996]
time:  01:44:36 [23169]
speed: 1.500000 m/sec
arrive-by: true
max xfers: 1
max time:  00:41:00
mode: transit
Repeated search with reversed request: 
-- Router Request --
from:  Den Haag, Van Speijkstraat [9702]
to:    Den Haag HS|4 [38996]
time:  01:44:36 [23169]
speed: 1.500000 m/sec
arrive-by: true
max xfers: 1
max time:  00:41:00
mode: transit
```

**Comment by koch-t** [comment] 2013-10-04 19:05
Seems to have been fixed with a new timetable.dat. Suspecting data problem.

**Closed as completed by koch-t** 2013-10-04 19:05 UTC
Labels: bug

**Comment by skinkie** [comment] 2013-10-04 19:07
Could we at least figure out what the problem is? And why it occurs?
